openapi: 3.0.1
info:
  title: 4D- Asset Management
  version: 2021-12
servers:
  - url: https://wlx4mlpzyl-vpce-01988d3d83bebbf0e.execute-api.eu-west-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: dev
    x-amazon-apigateway-endpoint-configuration:
      vpcEndpointIds:
        - vpce-01988d3d83bebbf0e
x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
    - Sid: AllowVPCEndpointToInvoke
      Effect: Allow
      Principal:
        AWS: "*"
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:eu-west-1:989486103510:wlx4mlpzyl/*/*/*
      Condition:
        StringEquals:
          aws:sourceVpce: vpce-01988d3d83bebbf0e
    - Sid: InvokeLambda
      Effect: Allow
      Principal:
        AWS: "*"
      Action: lambda:InvokeFunction
      Resource: lambda.amazonaws.com
