openapi: 3.0.1
info:
  title: PrivateApiGateway
  version: "2021-12-09T13:46:03Z"
servers:
  - url: https://wlx4mlpzyl.execute-api.eu-west-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: dev
    x-amazon-apigateway-endpoint-configuration:
      vpcEndpointIds:
        - vpce-01988d3d83bebbf0e
paths:
  /projects:
    get:
      tags:
        - Projects
      responses:
        "200":
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/project_data"
        "400":
          description: Error in getting Projects
          content:
            application/json:
              examples:
                projects:
                  value: Error in Getting Projects
  /project:
    post:
      tags:
        - Projects
      requestBody:
        $ref: "#/components/requestBodies/project_data"
      responses:
        "200":
          description: Project has been added successfully
        "400":
          description: Error in adding a new Project
  /phases:
    get:
      tags:
        - Phases
      responses:
        "200":
          description: A list of phases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/phase_data"
        "400":
          description: Error in getting Phases
          content:
            application/json:
              examples:
                projects:
                  value: Error in Getting Phases
  /phase:
    post:
      tags:
        - Phases
      requestBody:
        $ref: "#/components/requestBodies/phase_data"
      responses:
        "200":
          description: Phase has been added successfully
        "400":
          description: Error in adding a new Phase
  /tags:
    get:
      tags:
        - Tags
      responses:
        "200":
          description: A list of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/tag_data"
        "400":
          description: Error in getting Tags
          content:
            application/json:
              examples:
                projects:
                  value: Error in Getting Tags
  /tag:
    post:
      tags:
        - Tags
      requestBody:
        $ref: "#/components/requestBodies/tag_data"
      responses:
        "200":
          description: Tag has been added successfully
        "400":
          description: Error in adding a new Tag
  /seasons:
    get:
      tags:
        - Seasons
      responses:
        "200":
          description: A list of Seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/season_data"
        "400":
          description: Error in getting Seasons
          content:
            application/json:
              examples:
                projects:
                  value: Error in Getting Seasons
  /season:
    post:
      tags:
        - Seasons
      requestBody:
        $ref: "#/components/requestBodies/season_data"
      responses:
        "200":
          description: Season has been added successfully
        "400":
          description: Error in adding a new Season
components:
  requestBodies:
    project_data:
      description: Request to add a new project.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/project_data"
    season_data:
      description: Request to add a new season.
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/season_data"
    phase_data:
      description: Request to add a new phase .
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/phase_data"
    tag_data:
      description: Request to add a new tag.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/tag_data"
  schemas:
    project_data:
      type: object
      properties:
        ProjectName:
          type: string
        Author:
          type: string
        Description:
          type: string
        CoverImage:
          type: string
        Season:
          $ref: "#/components/schemas/season_data"
        Phase:
          $ref: "#/components/schemas/phase_data"
        Tags:
          type: array
          items:
            $ref: "#/components/schemas/tag_data"
    season_data:
      type: object
      properties:
        ID:
          type: string
        CreationDateTime:
          type: string
        Name:
          type: string
    phase_data:
      type: object
      properties:
        ID:
          type: string
        CreationDateTime:
          type: string
        Name:
          type: string
    tag_data:
      type: object
      properties:
        ID:
          type: string
        CreationDateTime:
          type: string
        Name:
          type: string
x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
    - Sid: AllowVPCEndpointToInvoke
      Effect: Allow
      Principal:
        AWS: "*"
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:eu-west-1:989486103510:wlx4mlpzyl/*/*/*
      Condition:
        StringEquals:
          aws:sourceVpce: vpce-01988d3d83bebbf0e
    - Sid: InvokeLambda
      Effect: Allow
      Principal:
        AWS: "*"
      Action: lambda:InvokeFunction
      Resource: lambda.amazonaws.com
