version: "3.0"
services:
  localstack:
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_NETWORK=bridge
      - LAMBDA_REMOTE_DOCKER=0
      - LAMBDA_MOUNT_CODE=1
      - DYNAMODB_SHARE_DB=1
      - SERVICES=s3,lambda,cloudformation,apigateway,dynamodb,ec2,iam
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - PORT_WEB_UI=8080
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
